//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSDL : DbContext
    {
        public CSDL()
            : base("name=CSDL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chucvu> Chucvus { get; set; }
        public virtual DbSet<GoiTap> GoiTaps { get; set; }
        public virtual DbSet<Hopdong> Hopdongs { get; set; }
        public virtual DbSet<LichSu> LichSus { get; set; }
        public virtual DbSet<lichtap> lichtaps { get; set; }
        public virtual DbSet<Ngay> Ngays { get; set; }
        public virtual DbSet<PT> PTs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<ThoiGian> ThoiGians { get; set; }
        public virtual DbSet<TTKH> TTKHs { get; set; }
        public virtual DbSet<TTNV> TTNVs { get; set; }
    }
}
