//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadon()
        {
            this.hoadonchitiets = new HashSet<hoadonchitiet>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> tongtien { get; set; }
        public Nullable<int> giamgia { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonchitiet> hoadonchitiets { get; set; }
    }
}
