//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSu
    {
        public int id { get; set; }
        public Nullable<int> idnv { get; set; }
        public Nullable<int> idkh { get; set; }
        public Nullable<int> maso { get; set; }
        public string noidung { get; set; }
        public Nullable<double> tien { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    
        public virtual TTNV TTNV { get; set; }
    }
}
