//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichtap
    {
        public int id { get; set; }
        public Nullable<int> idhopdong { get; set; }
        public Nullable<int> idngay { get; set; }
        public Nullable<int> idtime { get; set; }
    
        public virtual Hopdong Hopdong { get; set; }
        public virtual Ngay Ngay { get; set; }
        public virtual ThoiGian ThoiGian { get; set; }
    }
}
