//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.hoadonchitiets = new HashSet<hoadonchitiet>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> idncc { get; set; }
        public Nullable<int> idloai { get; set; }
        public Nullable<int> giatien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonchitiet> hoadonchitiets { get; set; }
        public virtual loai loai { get; set; }
        public virtual nhacungcap nhacungcap { get; set; }
    }
}
